# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190307_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute_value',
        ),
    ]
