# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190308_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='attribute_value',
            new_name='attributevalue',
        ),
    ]
