# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-09 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190308_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='cart_id',
        ),
    ]
