# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-10 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_shoppingcart_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders_list', to='shop.Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_orders_list', to='shop.Shipping'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tax_orders_list', to='shop.Tax'),
        ),
    ]
